name: Test actions policies

on: [workflow_dispatch]

jobs:
  public-action-same-org:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Execute action in public repo'
        uses: wizard-whitebeard/public-action@master

  public-action-same-ent:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Execute action in public repo'
        uses: odlulu/public-action@master

  internal-action-same-ent:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Execute action in public repo'
        uses: odlulu/internal-action@master

  private-action-same-ent:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Execute action in public repo'
        uses: odlulu/private-action@master
  
  public-action-different-ent:
    runs-on: ubuntu-latest
    
    steps:
        - uses: jenschelkopf/broadcast-action@1.0


  created-by-github:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  verified-creator:
    runs-on: ubuntu-latest
    
    steps:
      - uses: atlassian/gajira-cli@master
