name: Release
on:
  workflow_call:
#     inputs:
#       environment:
#         type: string
#         required: false
#         default: staging
    secrets:
      PAT:
        required: true

jobs:
  deploy_to_review:
    name: Deploy Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Dump inputs
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: echo "$INPUTS"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  deploy_to_staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/main'
    steps:
      - name: Dump inputs
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: echo "$INPUTS"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  deploy_to_production:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment: production
    if: github.event.ref == 'refs/heads/main'
    needs: deploy_to_staging
    steps:
      - name: Checkout a private repo
        uses: actions/checkout@v2
        with:
          repository: wizard-whitebeard/private-repo
          ref: main
          token: ${{ secrets.PAT }}
