name: Release
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: false
        default: staging
    secrets:
      PAT:
        required: true

jobs:

  deploy_to_production:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
      url: https://github.com

    steps:
      - name: Checkout a private repo
        uses: actions/checkout@v2
        with:
          repository: wizard-whitebeard/private-repo
          ref: main
          token: ${{ secrets.PAT }}
