name: Release
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: false
        default: staging
    secrets:
      environment_token:
        required: true

jobs:

  deploy_to_production:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
      url: https://github.com

    steps:
      - name: Dump secret
        run: echo ${{ secrets.environment_token }}
      - name: Dump inputs
        env:
          INPUTS: ${{ toJson(inputs) }}
        run: echo "$INPUTS"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
